#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

if git diff HEAD~ HEAD --name-only | grep -E '^(package-lock\.json|yarn\.lock)$'; then
  echo "Detected changes in dependencies, executing npm install..."
  npm install
fi

